#!/bin/bash

# Determine path of profile directories
SLURM_CFG_PATH=~/.config/snakemake
if [ $# -eq 1 ] ; then
    SLURM_CFG_PATH=$SLURM_CFG_PATH/$1
else
    SLURM_CFG_PATH=$SLURM_CFG_PATH/slurm
fi

# Copy updated scripts into profile directories
cp -rf ./slurm-generic/*.py $SLURM_CFG_PATH
