# ==============================================================================
#                           SNAKEMAKE RUNTIME ARGUMENTS
# ==============================================================================

# Values for slurm parameters to use with all jobs, using executor keywords
# See https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html#advanced-resource-specifications for a list of all available parameters
# Syntax is <slurm_parameter>: value.
default-resources:
    slurm_partition: 'cpu'  # SLURM partition to use in job submission. Use 'sinfo' to check available partitions ('cpu' or 'gpu' on Curnagl/Urblauna)
    slurm_account: 'user_account'  # SLURM account to use in job submission. Use 'Sproject' to check available accounts
    # slurm_extra: "'--mail-type=ALL --mail-user=<your email>'"  # SLURM extra arguments (QoS, mail type and address... see https://slurm.schedmd.com/sbatch.html for a complete list) in string format
    # Can also accomodate for global resource settings:
    # cpus_per_task: 2  # Number of CPUs for the job
    # mem_mb: 1024  # Memory in MB
    # runtime: 480  # Runtime in minutes

# Rule-specific resources, using executor keywords
set-resources:
    <rulename>:
        slurm_partition: 'other partition'  # Partition differing from default
        slurm_extra: "'--mail-type=ALL'"  # Extra Slurm arguments
        mem_mb: 1024  # Memory in MB
        runtime: 60  # Runtime in minutes

# Rule-specific number of CPUs, using Snakemake keywords
set-threads:
    <rule_name>:
        threads: 24

# Path to directory to store SLURM logs
slurm-logdir: '/path/to/slurm/logs'

# Keep SLURM logs even when job is successful (True/False)
slurm-keep-successful-logs: True

# Maximum number of jobs to submit concurrently (can be 'unlimited' or a number)
jobs: 500

# Number of cores used by local snakemake rules
local-cores: 1

# Maximum number of jobs to submit per timespan. Format: <number>/<timespan>
max-jobs-per-timespan: '150/1s'  # Currently bugged, so use a high value for now

# Maximum number of job status checks per second
max-status-checks-per-second: 10

# Number of times Snakemake tries to restart a failed job
restart-times: 1



# ==============================================================================
#                            DO NOT EDIT THIS SECTION
# ==============================================================================

# Executor to use for job submission
executor: 'slurm'
